openapi: 3.2.0
info:
  title: Infrahub Calculate API
  version: '1.0'
  description: Calculate APIs
servers:
- url: https://infrahub-api.nexgencloud.com/v1
security:
- accessToken: []
- apiKey: []
tags:
- name: Calculate
  description: Calculate APIs
paths:
  /pricebook/calculate/resource/{resource_type}/{id}:
    get:
      tags:
      - Calculate
      summary: Retrieve Billing Rate for Resource
      description: Calculate the hourly billing rate of a specified resource by including the resource ID in the path.
      operationId: Calculate_resource_billing_rate
      parameters:
      - name: resource_type
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Successfully retrieved billing rate.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceBillingResponseForCustomer'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseModel'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseModel'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseModel'
        '500':
          description: Internal Server Error
          content: {}
      security:
      - accessToken: []
      - apiKey: []
components:
  schemas:
    InfrahubResourceObjectResponseForCustomer:
      type: object
      properties:
        type:
          type: string
        name:
          type: string
        infrahub_id:
          type: integer
        status:
          type: string
        host:
          type: string
        resources:
          type: array
          items:
            $ref: '#/components/schemas/PricebookResourceObjectResponseForCustomer'
        price:
          type: number
        actual_price:
          type: number
    ResourceObjectResponseForCustomer:
      type: object
      properties:
        org_id:
          type: integer
        resource:
          $ref: '#/components/schemas/InfrahubResourceObjectResponseForCustomer'
    ResourceBillingResponseForCustomer:
      type: object
      properties:
        status:
          type: boolean
        message:
          type: string
        calculated_resource_bills:
          $ref: '#/components/schemas/ResourceObjectResponseForCustomer'
    ErrorResponseModel:
      type: object
      properties:
        status:
          type: boolean
          default: false
        message:
          type: string
        error_reason:
          type: string
    PricebookResourceObjectResponseForCustomer:
      type: object
      properties:
        type:
          type: string
        name:
          type: string
        amount:
          type: integer
        rate:
          type: number
        discounted_rate:
          type: number
        price:
          type: number
        actual_price:
          type: number
  securitySchemes:
    accessToken:
      type: apiKey
      description: Bearer Token
      name: Authorization
      in: header
    apiKey:
      type: apiKey
      description: Send it as api_key in header
      name: api_key
      in: header
x-original-swagger-version: '2.0'
