openapi: 3.2.0
info:
  title: Infrahub Regions API
  version: '1.0'
servers:
- url: https://infrahub-api.nexgencloud.com/v1
security:
- accessToken: []
- apiKey: []
tags:
- name: Regions
paths:
  /object-storage/regions:
    get:
      tags:
      - Regions
      summary: Get a list of supported regions
      operationId: listRegionsEndpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/object_storage__RegionListResponse'
        '422':
          description: Validation Error
          content: {}
components:
  schemas:
    object_storage__RegionResponse:
      title: RegionResponse
      required:
      - name
      type: object
      properties:
        name:
          title: Name
          type: string
    object_storage__RegionListResponse:
      title: RegionListResponse
      required:
      - regions
      type: object
      properties:
        regions:
          title: Regions
          type: array
          items:
            $ref: '#/components/schemas/object_storage__RegionResponse'
  securitySchemes:
    accessToken:
      type: apiKey
      description: Bearer Token
      name: Authorization
      in: header
    apiKey:
      type: apiKey
      description: Send it as api_key in header
      name: api_key
      in: header
x-original-swagger-version: '2.0'
