openapi: 3.2.0
info:
  title: Infrahub Health API
  version: '1.0'
servers:
- url: https://infrahub-api.nexgencloud.com/v1
security:
- accessToken: []
- apiKey: []
tags:
- name: Health
paths:
  /object-storage/healthz:
    get:
      tags:
      - Health
      summary: Healthcheck
      operationId: healthzEndpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/object_storage__HealthResponse'
        '422':
          description: Validation Error
          content: {}
components:
  schemas:
    object_storage__HealthResponse:
      title: HealthResponse
      required:
      - status
      type: object
      properties:
        status:
          title: Status
          type: string
  securitySchemes:
    accessToken:
      type: apiKey
      description: Bearer Token
      name: Authorization
      in: header
    apiKey:
      type: apiKey
      description: Send it as api_key in header
      name: api_key
      in: header
x-original-swagger-version: '2.0'
