openapi: 3.2.0
info:
  title: Infrahub Alive API
  version: '1.0'
servers:
- url: https://infrahub-api.nexgencloud.com/v1
security:
- accessToken: []
- apiKey: []
tags:
- name: Alive
paths:
  /billing/alive:
    get:
      tags:
      - Alive
      summary: 'GET: Alive'
      description: Retrieve the billing status of your account to ensure that it is active. An active billing status ensures uninterrupted service. For additional information **click here**.
      operationId: Get_alive
      responses:
        '200':
          description: Success
          content: {}
      security:
      - accessToken: []
      - apiKey: []
  /billing/alive/doc:
    get:
      tags:
      - Alive
      operationId: Get_alive_doc
      responses:
        '200':
          description: Success
          content: {}
      security:
      - accessToken: []
      - apiKey: []
      summary: Get alive doc
      x-summary-source: derived
components:
  securitySchemes:
    accessToken:
      type: apiKey
      description: Bearer Token
      name: Authorization
      in: header
    apiKey:
      type: apiKey
      description: Send it as api_key in header
      name: api_key
      in: header
x-original-swagger-version: '2.0'
